### ISSUE TITLE
New release needed for Ansible Galaxy

### ISSUE THREAD

**Issue by 00willo** [f500/ansible-dumpall#12]
It would be great for a new release to be rolled.  Specifically, so PR#11 is zipped up and then available to ansible galaxy.  This is a handy little role, thanks.

**Comment by ramondelafuente** [comment]
Wow. Only took over a year to see this issue. Sorry about that :O 

Rolling a new relase now.

**Comment by 00willo** [comment]
Thanks, appreciate it.
